name: Node.js CI
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

env:
  SIGNER_ADDRESS: tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6
  TEZOS_RPC: https://sandbox.hangzhounet.gravity.earth

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test project
        env:
          SIGNER_PRIVATE: ${{ secrets.SIGNER_PRIVATE }}
        run: |
          echo $SIGNER_PRIVATE
          npm run test
